basic.forever(function () {
    basic.showNumber(1)
    basic.pause(500)
    basic.showNumber(2)
    basic.pause(500)
    basic.showNumber(3)
    basic.pause(500)
    basic.showNumber(4)
    basic.pause(500)
    basic.showNumber(5)
    basic.pause(500)
    basic.showNumber(6)
    basic.pause(500)
})
